// Games
export const SET_GAMES="SET_GAMES";
export const SET_GAMES_LOADING="SET_GAMES_LOADING";
export const SET_GAMES_ERROR="SET_GAMES_ERROR";

export const SET_GAME="SET_GAME";
export const SET_GAME_LOADING="SET_GAME_LOADING";
export const SET_GAME_ERROR="SET_GAME_ERROR";

export const ADD_GAME="ADD_GAME";
export const ADD_GAME_LOADING="ADD_GAME_LOADING";
export const ADD_GAME_ERROR="ADD_GAME_ERROR";

export const SET_GENRES="SET_GENRES";
export const SET_GENRES_LOADING="SET_GENRES_LOADING";
export const SET_GENRES_ERROR="SET_GENRES_ERROR";

export const SET_PLATFORMS="SET_PLATFORMS";
export const SET_PLATFORMS_LOADING="SET_PLATFORMS_LOADING";
export const SET_PLATFORMS_ERROR="SET_PLATFORMS_ERROR";

export const FILTER_GAMES="FILTER_GAMES";
export const ORDER_GAMES="ORDER_GAMES";
export const PAGINATE_GAMES="PAGINATE_GAMES";




